### ISSUE TITLE
How to link to heading or block in unknown note is undocumented

### ISSUE THREAD

**Issue by colintedford** [obsidianmd/obsidian-help#599] opened 2023-10-15 02:01 UTC
> There is already a built in suggestion for all headers in your vault.
> You can activate it by typing `[[##`.
> `[[#` is already used for all header in your current file.

— https://forum.obsidian.md/t/linking-headings/37021/2?u=cawlinteffid

The above is missing from https://help.obsidian.md/Linking+notes+and+files/Internal+links (reported by @hunanbean https://discord.com/channels/686053708261228577/694233507500916796/1162928423417688104).

The similar `^^` technique for block links is also undocumented.

**Comment by sigrunixia** [comment] 2023-10-15 04:02
Not sure if this NEEDS the images, but this has been added in two callouts, since it's a little bit more of a shortcut. Thoughts on this implementation before the issue is considered resolved?

![CleanShot 2023-10-14 at 23 00 12@2x](https://github.com/obsidianmd/obsidian-help/assets/68425372/1e73fe47-a882-4726-8072-2da7f58de978)

![CleanShot 2023-10-14 at 23 01 03@2x](https://github.com/obsidianmd/obsidian-help/assets/68425372/f1fc5e07-ab4c-4013-9fc5-9762b3058699)

**Comment by sigrunixia** [comment] 2023-10-18 16:52
I need to zoom in the screenshots, but otherwise this is considered as completed by the team. :)

**Comment by colintedford** [comment] 2023-10-18 19:36
Works for me. 🙂 Thanks!

**Comment by sigrunixia** [comment] 2023-10-28 22:24
This should be closed by #612

**Closed by sigrunixia** 2023-10-28 22:24 UTC
