### ISSUE TITLE
Card content on landing page overflow

### ISSUE THREAD

**Issue by mProjectsCode** [obsidianmd/obsidian-help#585] opened 2023-09-25 19:16 UTC
With normal zoom the cards overflow at the top.
![image](https://github.com/obsidianmd/obsidian-help/assets/61602848/3e4c2c60-4dbd-40c9-9562-500754676c59)

With more zoom the cards completely overflow.
![image](https://github.com/obsidianmd/obsidian-help/assets/61602848/1d35b241-7141-438b-8d65-87a2aac5ed53)

**Comment by kepano** [comment] 2023-11-09 00:05
I am unable to reproduce this. What OS/platform are you using?

**Comment by mProjectsCode** [comment] 2023-11-09 09:53
Windows and firefox

**Comment by mProjectsCode** [comment] 2023-11-10 10:14
![image](https://github.com/obsidianmd/obsidian-help/assets/61602848/45cd3dc6-27c5-4dc2-9f0a-68cbcd249ba7)
100% zoom

![image](https://github.com/obsidianmd/obsidian-help/assets/61602848/e4316bd0-50b4-4613-b98a-6fc46113413d)
90% zoom

Still happens

**Comment by kepano** [comment] 2023-11-10 17:23
The cause of this issue is that Firefox does not yet support `:has()` selectors. Will look into it further.

**Comment by kepano** [comment] 2023-12-01 17:47
This should be fixed now

**Closed by kepano** 2023-12-01 17:47 UTC
